# cfg.py
# Edit strings on the right, but leave them in quotes.

#config for dg_yt_scraper.py
SCRAPE_URL = 'https://6um.digitalgangster.com/t/xxx/'

THREAD_LEN = 666

#config for strip_dupes.py (optional)
#infile should take the text file generated by dg_yt_scraper.py
#outfile can be whatever you'd like.
INFILE = 'url_list.txt'

OUTFILE = 'url_list_no_dupe.txt'

#config for yt_playlist_creator.py
#url_txt_file can be the txt file generated with strip_dupes, or dg_yt_scraper.
#url_txt_file must be in same directory as this python file.
EMAIL = "xxx@gmail.com"

PASSWORD = "mypassword"

LIST_URL = "https://www.youtube.com/playlist?list=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

URL_TXT_FILE = "url_list_no_dupe.txt"
